spring.application.name=backend
server.port=8080

# Configuración de Conexión a MariaDB
# Inyectamos la URL, el usuario y la contraseña desde el entorno
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

# Configuración de MailSender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configuración de Stripe
stripe.key.secret=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

# Configuración de JWT
jwt.secret=${JWT_SECRET}

# Captcha
google.recaptcha.secret=${RECAPTCHA_SECRET}

# Prometheus + Grafana
management.endpoints.web.exposure.include=prometheus,health
management.endpoint.prometheus.access=read_only
management.prometheus.metrics.export.enabled=true

# Nombre de la app que aparecerá en Grafana
management.metrics.tags.application=${spring.application.name}